# Generated by Django 4.2.1 on 2023-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudservice',
            name='description',
            field=models.TextField(),
        ),
    ]
